services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api  
    container_name: juegos-salo-api
    ports:
      - "3000:3000"

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - api